TARGET_URL = "http://localhost:3000"

REQUEST_TIMEOUT = 3

NORMAL_MIN_DELAY = 0.5
NORMAL_MAX_DELAY = 2.0

SPIKE_WORKERS = 20
SPIKE_REQUESTS_PER_BATCH = 50

GRADUAL_START_RATE = 2
GRADUAL_MAX_RATE = 30